mars/urls.py
from django.contrib import admin
from django.conf.urls import url, include

urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^',include('pre_login.urls')),
    url(r'^quiz/',include('post_login.urls')),
]

post_login/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [
    url(r'^student.html$', views.student , name="student"),
    url(r'^project_m.html$', views.project_m , name="project_m"),
    url(r'^list_stu.html$', views.student_details , name="student_details"),
]

pre_login/urls.py
from django.conf.urls import url, include
from . import views
urlpatterns = [
    url(r'^$', views.login, name="login"),
    url(r'^registration.html', views.register, name="registration"),
]

post_login/models.py
from django.db import models

# Create your models here.

pre_login/models.py
from django.db import models
# from django.contrib.auth.models import User
from django import forms
# forms.Select(widget=forms.Select)

class Personal_Details(models.Model):
    username = models.CharField(max_length = 100)
    Email = models.EmailField(primary_key=True,unique=True)
    Age = models.IntegerField(default=19,null=False)
    City = models.CharField(max_length = 50)
    State = models.CharField(max_length = 50)
    Country = models.CharField(max_length = 30)
    Occupation = models.CharField(max_length = 30)
    Password = models.CharField(max_length = 50)
    Project_Manager = models.BooleanField(default="False")
    Student = models.BooleanField(default="False")


    def __str__(self):
        return self.Email




        

post_login/forms.py
from django import forms
from django.db import models
from .models import Questions
from django.forms.widgets import RadioSelect

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Questions
        fields = ["question","option1","option2","option3","option4","answer"]
        Radio_Choices = ["option1", "option2", "option3", "option4"]
        radio = forms.ChoiceField( widget=RadioSelect(), choices=Radio_Choices)


        

pre_login/forms.py
from django import forms
from django.db import models
from .models import Personal_Details
from django.forms.widgets import RadioSelect
# class DesignForm(models.Model):
#     username = models.CharField(max_length = 100)
#     Email = models.EmailField(primary_key=True,unique=True)
#     Age = models.IntegerField(default=19,null=False)
#     City = models.CharField(max_length = 50,default="Bangalore")
#     State = models.CharField(max_length = 50)
#     Country = models.CharField(max_length = 30,default="India")
#     Occupation = models.CharField(max_length = 30)
#     Password = models.CharField(max_length = 50)


class RegistrationForm(forms.ModelForm):
    username = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder':'Username'}))
    Email = forms.EmailField(label='',widget=forms.TextInput(attrs={'placeholder':'Email'}))
    Age = forms.IntegerField(label='',widget=forms.TextInput(attrs={'placeholder':'Age'}))
    City = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder':'City'}))
    State = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder':'State'}))
    Country = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder':'Country'}))
    Occupation = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder':'Occupation'}))
    Password = forms.CharField(label='',widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    Radio_Choices = [("Project_Manager","Project_Manager"),("Student","Student")]
    Choose = forms.ChoiceField( widget=RadioSelect(), choices=Radio_Choices)
    class Meta:
        model = Personal_Details
        fields = ["username","Email","Age","City","State","Country","Occupation","Password"]#,"confirm password"
class LoginForm(forms.Form):
    Email = forms.CharField(label='',widget=forms.TextInput(attrs={'placeholder':'Email'}))
    Password = forms.CharField(label='',widget=forms.PasswordInput(attrs={'placeholder':'Password'}))
    Radio_Choices = [("Project_Manager","Project_Manager"),("Student","Student")]
    Choose = forms.ChoiceField( widget=RadioSelect(), choices=Radio_Choices)
    class Meta:
        model = Personal_Details
        fields = ["Email","Password","Project_Manager", "Student"] 
    

post_login/views.py
from django.shortcuts import render

from pre_login.forms import LoginForm
from pre_login.forms import RegistrationForm
from pre_login.models import Personal_Details
from django.http import HttpResponseRedirect
from django.utils.datastructures import MultiValueDictKeyError


def student(request):
    information = Personal_Details.objects.all()
    # print(information.get(Student="True"))
    info = Personal_Details.objects.get(Email=request.session['Email'])
    details = {"username" : info.username, "Age" : info.Age, "City":
    info.City, "State": info.State, "Country" : info.Country, "Occupation" : info.Occupation}
    return render(request,'quizes/student.html', details)

def project_m(request):
    info = Personal_Details.objects.get(Email=request.session['Email'])
    details = {"username" : info.username, "Age" : info.Age, "City":
    info.City, "State": info.State, "Country" : info.Country, "Occupation" : info.Occupation}
    return render(request,'quizes/project_m.html', details)

def student_details(request):
    information = Personal_Details.objects.all().filter(Student="True")
    print(information)
    diction = {'username' : []}
    for user in information:
        diction.get('username').append(user.username)
        print(diction)

    
    return render(request, 'quizes/list_stu.html', diction)

pre_login/views.py
from django.shortcuts import render
from .forms import RegistrationForm
from .forms import LoginForm
from .models import Personal_Details
from django.http import HttpResponseRedirect
from django.contrib import messages
# from .forms import RegistrationForm
# Create your views here.
def home(request):
    return render(request,'page/login.html')

def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            detail_item = form.save(commit="False")
            detail_item.save()
            form = LoginForm()
            return HttpResponseRedirect('/')
    else:
        form = RegistrationForm()   
    cont = {'form':form}
    return render(request,'page/registration.html',cont)

def login(request):
    if request.method == "POST":
        form = LoginForm(request.POST) 
        if form.is_valid():
            input_data = form.cleaned_data
            try:
                print(input_data["Email"])
                print(Personal_Details.objects.get(Email=input_data["Email"]).Password)
                obj = Personal_Details.objects.get(Email=input_data["Email"])
                # print(obj)
                # print("HELLLOOOOOOOOOOOO")
                
                # print("a")
                # print(obj.Project_Manager)
                
                # print(input_data['Choose'])
                # print(obj.Student)
                if(input_data['Choose']=="Project_Manager"):
                    if(obj.Password == input_data['Password']):
                        request.session['Email'] = obj.Email
                        request.session['username'] = obj.username
                        return HttpResponseRedirect("/quiz/project_m.html")

                if(input_data['Choose']=="Student"):
                    print("JANUUUUU")
                    if(obj.Password == input_data['Password']):
                        print("TIGERRR")
                        request.session['Email'] = obj.Email
                        request.session['username'] = obj.username
                        return HttpResponseRedirect("/quiz/student.html")
            except:
                print("Unidentified User")
    else:
        form = LoginForm()
    cont = {'form':form}
    return render(request,'page/login.html',cont)

post_login/templates/quizes/header.html
<!Doctype html>
<html lang="en">
<head>
    <title>Profile</title>
    <meta charset="utf-8">
    {% comment %} {% load staticfiles %} {% endcomment %}
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
    <meta name="viewport" content="width-device-width , initial scale=1.0">
    <style> 
    body
    {
        background-repeat:no-repeat;
        background-image: url("/static/img/123.jpg");
        background-color: black;
    }
    .topnav 
    {
        background-color: #333;
        overflow: hidden;
    }
    .topnav a 
    {
        float: left;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 17px;
    }
    .topnav a:hover 
    {
    background-color: #DC381E;
    color: black;
    }
    .topnav a.active {
        background-color: #DC381E;
        color: white;
    }
    </style>
</head>
<body>
    <div class="topnav">
        <a class="active" href="#">Home</a>
        <a href="/">Login</a> 
    </div>
    {% block content %}
    {% endblock %}
</body>
</html>

post_login/templates/quizes/list_stu.html
{% extends "quizes/header.html" %}
{% block content %}  
<style>
    #mainbox 
    {
        position: relative;
        padding :3em;
        padding-top :2em;
        border-radius: 40px;
        height: 25em;
        width: 25em;
        margin: auto;
        margin-top: 3em;
        border-style: ridge;
        align-content:center;
        background-color: rgb(0,0,0,0.4);
    }
    .row > div
    {
        border:0.1em solid white;
    }
    .heading
    {
        text-align: right;
    }
    </style>
</head>
<body style="font-size: 1.25em;">
    <h3 style="color:white; align:center">List Of Students</h3>
    <div class="container" id="mainbox">
    {%for i in username %}
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">Username:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ i }}</p>
            </div>
        </div>
    {%endfor%}
 
    
</body>
{% endblock %}

post_login/templates/quizes/project_m.html
{% extends "quizes/header.html" %}
{% block content %}  
<style>
    #mainbox 
    {
        position: relative;
        padding :3em;
        padding-top :2em;
        border-radius: 40px;
        height: 25em;
        width: 25em;
        margin: auto;
        margin-top: 3em;
        border-style: ridge;
        align-content:center;
        background-color: rgb(0,0,0,0.4);
    }
    .row > div
    {
        border:0.1em solid white;
    }
    .heading
    {
        text-align: right;
    }
    </style>
</head>
<body style="font-size: 1.25em;">
    <div class="container" id="mainbox">
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">Username:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ username }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">Age:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ Age }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">City:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ City }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">State:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ State }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">Country:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ Country }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">Occupation:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ Occupation }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">Position:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">Project Manager</p>
            </div>
        </div>
        <button type="button" onclick="window.location.href = 'list_stu.html'" >SHORTLIST</button>

    </div>
    
</body>
{% endblock %}

post_login/templates/quizes/student.html
{% extends "quizes/header.html" %}
{% block content %}  
<style>
    #mainbox 
    {
        position: relative;
        padding :3em;
        padding-top :2em;
        border-radius: 40px;
        height: 25em;
        width: 25em;
        margin: auto;
        margin-top: 3em;
        border-style: ridge;
        align-content:center;
        background-color: rgb(0,0,0,0.4);
    }
    .row > div
    {
        border:0.1em solid white;
    }
    .heading
    {
        text-align: right;
    }
    </style>
</head>
<body style="font-size: 1.25em;">
    <div class="container" id="mainbox">
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">Username:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ username }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">Age:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ Age }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">City:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ City }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">State:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ State }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">Country:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ Country }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">Occupation:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">{{ Occupation }}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-4 heading">
                <p style="color:white;">Position:</p>
            </div>
            <div class="col-8">
                <p style="color:white;">Student</p>
            </div>
        </div>
    </div>
</body>
{% endblock %}

pre_login/templates/page/header.html
<!Doctype html>
<html lang="en">

<head>
    <title>Mars_Ticket</title>
    <meta charset="utf-8">
    {% comment %} {% load staticfiles %} {% endcomment %}
    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
    <meta name="viewport" content="width-device-width , initial scale=1.0">

    <style type="text/css">
        html,
        body
        {
            background-color: black;
            background-image : url("mars.jpg");
            height:100%;
        } 
    </style>
    <style> 
    body {
        background-repeat:no-repeat;
        background-image: url("/static/img/123.jpg");
        }
        background-image{
            opacity = 0.1;
        }
        .topnav {
        background-color: #333;
        overflow: hidden;
        }
        .topnav a {
        float: left;
        color: #f2f2f2;
        text-align: center;
        padding: 14px 16px;
        text-decoration: none;
        font-size: 1em;
        }
        .topnav a:hover {
        background-color: #DC381E;
        color: black;
        }
        .topnav a.active {
        background-color: #DC381E;
        color: white;
        }
        .middle 
        {
            margin: 150px;
            height: 800px;
        }  
        input,
        .btn {
        width: 100%;
        padding: 12px;
        border: none;
        border-radius: 4px;
        margin: 5px 0;
        opacity: 0.85;
        display: inline-block;
        font-size: 17px;
        line-height: 20px;
        text-decoration: none; /* remove underline from anchors */
        }

        input:hover,
        .btn:hover {
        opacity: 1;
        }

        input[type=submit] {
        background-color: #DC381E;
        color: white;
        cursor: pointer;
        }

        input[type=submit]:hover {
        background-color: #DC381E;
        }  
    </style>
</head>

<body>
    
    <div class="topnav">
        <a class="active" href="{% url 'login' %}">Home</a>
        <a href="#">About</a>
    </div>
    {% block content %}
    {% endblock %}

</body>

</html>

pre_login/templates/page/login.html
{% extends "page/header.html" %}

{% block content %}
<style>
    #mainbox 
    {
        position: relative;
        padding :3em;
        padding-top :2em;
        border-radius: 40px;
        height: 30em;
        width: 30em;
        margin: auto;
        border-style: ridge;
        align-content:center;
        background-color: rgb(0,0,0,0.4);
    } 

    input,.btn 
    {
        size: 20em; 
        padding: 12px;
        border: none;
        border-radius: 4px;
        margin: 5px;
        opacity: 0.85;
        display: inline-block;
        font-size: 1em;
        line-height: 20px;
        text-decoration: none; 
    }
    input:hover,.btn:hover 
    {
        opacity: 1;
    }
    .allign
    {
        margin:auto;
        text-align: center;
        width:70%;
    }
    /* Create a custom radio button */
    .checkmark {
    position: absolute;
    top: 0;
    left: 0;
    height: 1em;
    width: 1em;
    background-color: #eee;
    border-radius: 50%;
    }
    #id_Choose>li{
        display: inline;
        color: white;
    }

</style>
<body stye="padding: 50em 0">
<div class="container-fluid" style="height: 100%;padding:10em 0;">
<div class="container" id="mainbox">
    <div class="row">
        <div class="col-12 allign">
            <h2 style="color:white;opacity: 1;">Login</h2>
        </div>
    </div>
    {% comment %} <div class="row justify-content-center">
        <div class="col-12 allign">
            <form action="/action_page.php">
                <input type="checkbox" name="choice 1" value="project_manager"> Project Manager <br>
                <input type="checkbox" name="choice 2" value="student"> Student <br>
            </form>
        </div>
    </div> {% endcomment %}
    <div class="row justify-content-center">
        <div class="col-12 allign">
            <form method="POST" action="" >
                {% csrf_token %}
                {{form}}
                {% comment %} <div class="row">
                    <div class="col-12">
                        <label class="row justify-content-center" style="color:white"> Project Manager
                        <input type="radio" name="radio" id= "o1" value="Project Manager">
                        <span class="checkmark"></span>
                        </label> 
                        <label class="row justify-content-center" style="color:white"> Student
                        <input type="radio" name="radio" id= "o2" value="Student">
                        <span class="checkmark"></span>
                        </label>
                    </div>
                </div> {% endcomment %}
                <input type="submit" value="Submit">
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-12 allign">
            <a href ="registration.html">Not A Member Yet? Click here to Register</a>
        </div>
    </div>
</div>
</div>
</body>
{% endblock %}

pre_login/templates/page/registration.html
{% extends "page/header.html" %}

{% block content %}
<style>
    #mainbox
    {
        position: relative;
        border-radius: 40px;
        border-style: ridge;
        height: 37em;
        width: 35em;
        margin: auto;
        margin-top: 3em;
        align-content:center;
        padding: 3em;
        padding-top: 1em;
        background-color: rgb(0,0,0,0.4);
    } 

    input,.btn 
    {
        /* padding: 12px; */
        border: none;
        border-radius: 4px;
        margin-left: auto;
        margin-right: auto;
        opacity: 0.85;
        display: inline-block;
        font-size: 1em;
        line-height: 20px;
        text-decoration: none;
    }

    input:hover,.btn:hover 
    {
        opacity: 1;
    }

    input[type=submit] 
    {
        background-color: #DC381E;
        color: white;
        cursor: pointer;
    }

    input[type=submit]:hover 
    {
    background-color: #DC381E;
    }

    .allign
    {
        margin:auto;
        text-align: center;
    }
    #id_Choose>li{
        display: inline;
        color: white;
    }
</style>
<body stye="padding: 5em 0">
    <div class="container" id="mainbox">
        <div class="row">
            <div class="col-12 allign">
                <h2 style="color:#f0f8ff">Enter your details</h2>
            </div>
        </div>
        <div class="row">
            <div class="col-12 allign">
                <form method="POST" action="">
                    {% csrf_token %}
                    {{form}}
                    <input type="submit" value="Submit">
                </form>
            </div>
        </div>
    </div>
{% endblock %}